channels:
  - conda-forge
dependencies:
  - python=3
  # install requires
  - astropy
  - h5py
  - numpy
  - unyt
  # develop requires
  - black
  - jupyterlab
  - nbconvert
  - nbsphinx
  - pylint
  - sphinx
  - sphinxcontrib-apidoc
