channels:
  - conda-forge
dependencies:
  - python=3
  # install
  - astropy
  - h5py
  - numpy
  - unyt
  # develop
  - tox
  ## code
  - black
  - jupyterlab
  - pylint
  - pytest
  ## doc
  - m2r
  - nbconvert
  - nbsphinx
  - sphinx
  - sphinxcontrib-apidoc
  ## release
  - setuptools
  - twine
  - wheel
